spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.57.133:3306/mybatis?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500




##spring boot2.x以后需增加initialization-mode: always 方可生效
##  schema:
##    - classpath:department.sql
##  initialization-mode: always
mybatis:
  config-location: classpath:mybatis/configuration-mybatis.xml
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
    #开启驼峰命名法匹配规则
server:
  port: 8990
logging:
  config: logback-spring.xml
  path: /home/developer/app/logs/
